name: CD - DigitalOcean Ubuntu

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: Production
    steps:
      - name: pulling git repository
        uses: actions/checkout@v3

      - uses: c-hive/gha-npm-cache@v1

      - name: Install JS dependencies
        run: npm install

      - name: build application
        run: |
          npm run build
          mv build html

      - name: copy file via ssh password
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.PROD_UBUNTU_IP }}
          username: ${{ secrets.PROD_UBUNTU_USERNAME }}
          password: ${{ secrets.PROD_UBUNTU_PASSWORD }}
          source: "./html/"
          target: "/var/www/bruno.buzz/"