name: CI - DigitalOcean Ubuntu

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: Production
    steps:
      - name: pulling git repository
        uses: actions/checkout@v3

      - uses: c-hive/gha-npm-cache@v1

      - name: Install JS dependencies
        run: npm install

      - name: Install sshpass
        run: sudo apt install sshpass

      - name: build application
        run: npm run build

      - name: copy file via ssh password
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.PROD_UBUNTU_IP }}
          username: ${{ secrets.PROD_UBUNTU_USERNAME }}
          password: ${{ secrets.PROD_UBUNTU_PASSWORD }}
          source: "./build/*"
          target: "/var/www/bruno.buzz/html"

      # - name: set authorization
      #   run: ssh -o StrictHostKeyChecking=no ${{ secrets.PROD_UBUNTU_USERNAME }}@${{ secrets.PROD_UBUNTU_IP }} uptime

      # - name: deploying to ubuntu server
      #   run: sshpass -p "${{ secrets.PROD_UBUNTU_PASSWORD }}" scp -r ./build/* ${{ secrets.PROD_UBUNTU_USERNAME }}@${{ secrets.PROD_UBUNTU_IP }}:/var/www/bruno.buzz/html